version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  python-flake8: &python-flake8
    lint-command: 'flake8 --ignore=E501 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  python-mypy: &python-mypy
    lint-command: 'mypy --show-column-numbers'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  python-black: &python-black
    format-command: 'black --quiet -'
    format-stdin: true

  python-isort: &python-isort
    format-command: 'isort --quiet -'
    format-stdin: true

  lua-lua-format: &lua-lua-format
    format-command: 'lua-format -i --double-quote-to-single-quote --spaces-inside-table-braces --break-before-table-rb --break-after-table-lb --chop-down-table --column-limit=120'
    format-stdin: true

languages:
  python:
  - <<: *python-flake8
  # - <<: *python-mypy
  - <<: *python-black
  - <<: *python-isort

  lua:
    - <<: *lua-lua-format
